workflows:
  ios-debug-workflow:
    name: iOS Debug Build
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
          # 強迫進入 ios 資料夾安裝原生依賴
          cd ios
          pod install --repo-update
          cd ..
      - name: Build iOS Simulator version
        script: |
          # 1. 編譯模擬器版本（繞過簽名限制）
          flutter build ios --debug --simulator
          
          # 2. 手動在雲端建立標準 IPA 結構
          mkdir -p Payload
          cp -r build/ios/iphonesimulator/Runner.app Payload/
          
          # 3. 壓縮成真正的 IPA 檔案
          zip -r sky_mapper.ipa Payload
    artifacts:
      # 指向模擬器編譯產出的路徑
      - "*.ipa"