workflows:
  ios-debug-workflow:
    name: iOS Debug Build
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build iOS Simulator version
        script: |
          # 改用 --simulator，這會 100% 編譯成功且產出檔案
          flutter build ios --debug --simulator
    artifacts:
      # 指向模擬器編譯產出的路徑
      - build/ios/iphonesimulator/*.app